### ISSUE TITLE
z mesh, manipulate mesh use factor work?

### ISSUE THREAD

**Issue by geophyzz** [eroots/pyMT#1]
[11/29/23 3:25 PM] Hanneson, Cedar (he, him | il, lui)
In the Z Mesh section of the Manipulate Mesh tab of the Mesh Designer, the "Use Factor" option doesn't seem to work? Am I doing something wrong or is only the "Use Decades" option functional?

**Comment by eroots** [comment]
You're right, it wasn't properly connected - it should be fixed now. I've also added a new tab to the mesh designer GUI (labelled 'Depths') which will show the depth intervals and layer thicknesses for sanity check purposes.

**Comment by geophyzz** [comment]
Thanks Eric!
