### ISSUE TITLE
some suggested induction arrow enhancements

### ISSUE THREAD

**Issue by geophyzz** [eroots/pyMT#2]
Trying out more complicated issues, now with a fancy figure :)
1. Induction arrow maps should have a legend that clarifies if the real part has been reversed.  Something like 'Real (rev.), Length '  would be fine instead of just 'Real, Length' as it is now (see figure)
2. Also would be good if legend makes it clear what colour is used for data and what is model response.  
3. Also would be helpful if one could turn off the real reversal to display the wiese convention
![HJ-L01-107-IV-Map-64Hz](https://github.com/eroots/pyMT/assets/55920444/929c1706-645e-4a02-ac84-f4299f2f8ee6)

**Comment by eroots** [comment]
All those suggestions have been added. The legend should properly update no matter how many arrows are shown, and a new menu item "Point Options -> Induction Arrows -> Convention" has been added to switch between Parkinson (default) and Weise.
