### ISSUE TITLE
Add Colorbar for Plot RMS in Map View

### ISSUE THREAD

**Issue by channeson** [eroots/pyMT#3]
Re: Data Plot > Show Map > Plot RMS
Point Options > RMS Plotting > Colours

When this option is used, a colorbar is needed.

I created one by adding the following code on line 1023 of **gplot.py** but it's not working properly.
(1) The colorbar appears, but the program crashes when a parameter is changed (e.g. cmap or markersize).
error message: "AttributeError: 'NoneType' object has no attribute"
(2) The point colours don't agree with the numerical values (see figure below; e.g. 0.83 and 0.97 are green, but 0.69-0.74 and 1.00 are orange, and 0.85 is dark orange; also, 1.45 and 2.16 are the same colour). I added a printout of these values to the code below so I could double check them.

Eric, I tried to create the colorbar in a similar way to how you did it elsewhere in pyMT. However, I'm new to python and clearly did something wrong. Could you please add a colorbar and make sure the correct RMS values are being plotted? Thanks!

        if self.plot_rms:
            if 'colour' in self.rms_plot_style:
                numsite = len(self.dataset.data.site_names)
                rms_val = np.empty(numsite)
                for jj, site in enumerate(self.dataset.data.site_names):
                    print('  '+self.dataset.data.site_names[jj])
                    print(' '+'{:5.2f}'.format(self.dataset.rms['Station'][site]['Total']))
                    rms_val[jj] = self.dataset.rms['Station'][site]['Total']
                min_rms = min(rms_val)
                max_rms = max(rms_val)
                fake_vals = np.linspace(min_rms, max_rms, numsite)
                self.fake_im = self.window['axes'][0].scatter(self.site_locations['all'][:,1],
                                                              self.site_locations['all'][:,0],
                                                              c=fake_vals, cmap=self.cmap)
                self.fake_im.set_visible(False)
                self.window['colorbar'] = self.window['figure'].colorbar(mappable=self.fake_im)
                self.window['colorbar'].set_ticks(np.linspace(min_rms, max_rms, 17))
                self.window['colorbar'].set_label("R.M.S. Misfit",labelpad=20,fontsize=self.label_fontsize)

![HJ_L01_107_Misfit_Colorbar_Labelled](https://github.com/eroots/pyMT/assets/68086022/426a39b1-44bb-4821-8f0d-204ee35a9fc9)

**Comment by eroots** [comment]
Good suggestion.
A colourbar has been added when plotting RMS by colour; an additional option has been added under "Point Options -> RMS Plotting" to include annotations for the RMS values.
It looks like you were on the right track, but a bug earlier in the code was causing the active sites (i.e., those currently being plotted in the data plot window) to have the wrong colours. This should now be fixed, and all colours should properly correspond to the new colourbar.
Note that this colourbar will still compete for space with any other ones (e.g., those made when plotting phase tensors). Several other plotting features still need to have colourbars added as well. I'll be looking into this at some point, but might open a new issue for that.
