### ISSUE TITLE
Formatting Updates to Model Viewer 2-D View

### ISSUE THREAD

**Issue by channeson** [eroots/pyMT#4]
Suggested updates for the 2-D View tab in Model Viewer

(1) Make all xlabels and ylabels visible (see lines 1658-1659, 1691, and 1700-1701 of **gplot.py**) by default.

(2) Add a title to the depth slice, including layer number and depth. I think a toggle would be nice, to give users two options.
(a) Depth = centre of layer
`ax.set_title('Layer '+str(z_slice)+', Depth = '+'{:.3g}'.format((self.model.dz[z_slice]+self.model.dz[z_slice-1])/2)+' km', fontsize=self.label_fontsize)`
(b) Depth = range of layer
`ax.set_title('Layer '+str(z_slice)+', Depth = '+'{:.3g}'.format(self.model.dz[z_slice-1])+u'\u2013'+'{:.3g}'.format(self.model.dz[z_slice])+' km', fontsize=self.label_fontsize)`
The above code can be added on line 1624 of **gplot.py** to produce the figure below.

(3) To avoid unintended cropping, the default parameters on lines 204-206 of **model_viewer.py** were updated:
`top=0.95, bottom=0.1, left=0.06, right=0.94, hspace=0.08, wspace=0.03`

(4) A resistivity colorbar in the bottom right panel (currently empty space) would be a very useful addition.

![XY125_L01_iter107_75_64_78](https://github.com/eroots/pyMT/assets/68086022/4422bff8-9bbe-42ad-834e-16784b0da290)

**Comment by eroots** [comment]
All suggestions have been implemented, including adding a menu item to set the plan view title to display either the center or range of the layer.
